#!/usr/bin/env bash

selection=$(fasd -a -R | awk '{print $2}' | rofi -dmenu -p "Find")                                                         

case "$selection" in
	/home/sd/Code/*  | \
	/home/sd/local/scripts/* )
		echo 'yes'
		code "$selection"
		;;
	*)
		xdg-open "$selection"
		;;
esac