#!/usr/bin/env bash
clips_dir=$LOCAL_DIR/xclips

file_name=$(rofi -dmenu -l 0 -p "Save Clipboard As")

if [ -n "$file_name" ]; then
    mkdir -p "$clips_dir"
    snip=$(xclip -o)

    echo "$snip" > "${clips_dir}/${file_name}"
fi