#!/usr/bin/env bash
clips_dir=~/local/xclips

primary=$(xclip -selection primary -o)

file_name=$( echo "$primary" | rofi -normal-window -dmenu -p "Save As")

if [ -n "$file_name" ]; then
    mkdir -p $clips_dir

    xclip -selection primary -o > "${clips_dir}/${file_name}"
fi