#!/usr/bin/env bash
clips_dir=~/local/xclips

file_name=$(rofi -dmenu -l 0 -p "Save Clipboard As")

if [ -n "$file_name" ]; then
    mkdir -p $clips_dir

    xclip -selection -o clipboard buffer-cut > "$clips_dir/$file_name"
fi