#!/usr/bin/env bash

search_query=$(rofi -dmenu -p "YAY Search")

if [[ -z "$query"]]; then
    eval $(terminal -T "YAY | Search and Install Packages" -hold -e yay "${search_query}"); exit 0
fi

kill -25 $PPID