#!/bin/sh

app="$1"
window_criteria="(?i)$app"

pid = $(`ps -C $app -o pid=`);

echo $pid
[[ "$(xdotool search --limit 1 --any --class --classname --role $app )" -eq 0  ]] && exec $app  

i3-msg "[class=\"$window_criteria\"] focus; [instance=\"$window_criteria\"] focus"