#!/usr/bin/env bash

#
# Focus or launch a program.
#
# EITHER switch focus to the running program matching on $1=$2, OR
# launch $5 with arguments ${@:6} on workspace $3 and output $4.
#

# Attempt to match the running program and obtain its window id.
case "$1" in
    (instance)        W=$(xdotool search --classname "$2" | head -1) ;;
    (class)           W=$(xdotool search --class "$2" | head -1)  ;;
    (title)           W=$(xdotool search --name "$2" | head -1) ;;
    (*)
    W='' ;;
esac   

cmd="[class=(?i)${2// /\\x20}] move scratchpad"
 
if [ -z "$W" ]; then
    # Launch the program because no matching window id was found.
    exec "${@:2}"
else
    # Focus the window.
    # Escape any whitespace to suit 'i3-msg'.
    #cmd="[$1=${2// /\\x20}] focus"

    cmd="${cmd}"
fi

i3-msg "${cmd}"