#!/usr/bin/env bash

#
# Focus or launch a program.
#
# EITHER switch focus to the running program matching on $1=$2, OR
# launch $5 with arguments ${@:6} on workspace $3 and output $4.
#

# Attempt to match the running program and obtain its window id.
$name='kitty'
$app="${@:2}"

case "$name" in
    (instance)        W=$(xdotool search --classname "$2" | head -1) ;;
    (class)           W=$(xdotool search --class "$2" | head -1)  ;;
    (title)           W=$(xdotool search --name "$2" | head -1) ;;
    (*)
    W='' ;;
esac   

cmd="[class=(?i)${2// /\\x20}] scratchpad show"
 
if [ -z "$W" ]; then
    # Launch the program because no matching window id was found.
    exec "${app}"
    i3-msg "mark ${name}, move scratchpad"
fi

i3-msg "${cmd}"