#!/bin/sh

name="$1"
app="${@:2}"

case "$name" in
    (instance)        W=$(xdotool search --classname "$2" | head -1) ;;
    (class)           W=$(xdotool search --class "$2" | head -1)  ;;
    (title)           W=$(xdotool search --name "$2" | head -1) ;;
    (*)
    W='' ;;
esac 

echo $W

cmd="[class=(?i)${2// /\\x20}] scratchpad show"

window_instance="[instance=${name}]"
cmd="${@:2}"

eval $TERMINAL --class $name --title $name --hold --command $cmd