#!/bin/sh

terminal=${TERMINAL:-$(command -v kitty)}

$terminal --hold -e "$@"       

# echo "$terminal $( [[ $hold_flag ]] && echo '--hold' ) -e $@"

# $terminal $( [[ $hold_flag ]] && echo '--hold' ) -e $@