#!/bin/sh

terminal=${TERMINAL:-$(command -v urxvt)}

echo $term_options

$terminal -e "$@"       

# echo "$terminal $( [[ $hold_flag ]] && echo '--hold' ) -e $@"

# $terminal $( [[ $hold_flag ]] && echo '--hold' ) -e $@