#!/bin/sh

terminal=${TERMINAL:-$(command -v urxvt)}

$terminal --hold -e "$@"     

# echo "$terminal $( [[ $hold_flag ]] && echo '--hold' ) -e $@"

# $terminal $( [[ $hold_flag ]] && echo '--hold' ) -e $@