#!/usr/bin/env bash

id=$(xdo id -n scratchterm);
if [ -z "$id" ]; then
  urxvtc -name scratchterm -e zsh -c "tmux new-session -A -s dummy";
   exec i3-msg [instance="scratchterm"] move position 10px 0px, resize set 99ppt 60ppt;
else
  action='hide';
  if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
    action='show';
  fi
  xdo $action -n scratchterm
  exec i3-msg [instance="scratchterm"] move scratchpad, scratchpad show, focus
fi 