#!/usr/bin/env bash

name="$1"
id=$(xdo id -n "$name");

cmd="[instance=${name}] move scratchpad"
if [ -z "$id" ]; then
   alacritty --class "scratchterm" -e zsh -c "tmux new-session -A -s dummy";
   cmd="${cmd}, scratchpad show"
else
  if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
    cmd="${cmd}, scratchpad show"
  fi
fi  
exec i3-msg "$cmd"
