#!/usr/bin/env bash

name="$1"
id=$(xdo id -n "$name")

echo "$id"

window_instance="[instance=${name}]"

if [ -z "$id" ]; then
	  alacritty --class $name -e zsh -ic "tmux new-session -A -s dummy"
	  cmd="move scratchpad, scratchpad show"
else
	action='hide';

	if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
		action='show';
	fi

	xdo $action -n "$id"

	cmd="scratchpad show"
fi

i3-msg "${window_instance} ${cmd}"
