#!/usr/bin/env bash

id=$(xdo id -n scratchterm);
if [ -z "$id" ]; then
   urxvtc -name scratchterm -e zsh -c "tmux new-session -A -s dummy";
   exec i3-msg [instance="scratchterm"] move position 20px 20px, resize set 98ppt 50ppt;
else
  action='hide';
  if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
    action='show';
  fi
  xdo $action -t "$id"
  exec i3-msg [instance="scratchterm"] move scratchpad, scratchpad show, focus
fi 