#!/usr/bin/env bash

id=$(xdo id -n $1);

if [ -z "$id" ]; then
	  urxvtc -name "$id" -e "tmux new-session -A -s dummy";
  else
	action='hide';

	if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
		action='show';
	fi

	xdo $action -n "$id"
	exec i3-msg [instance="$id"] focus;
fi
