#!/usr/bin/env bash

name="kitty"
id=$(xdo id -n $1)

window_instance="[instance=${name}]"

if [ -z "$id" ]; then
	  "$TERMINAL" --name "$name" --detach --hold -e zsh -ic "tmux new-session -A -s dummy"
	  cmd="move scratchpad, scratchpad show"
  else
	action='hide';

	if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
		action='show';
	fi

	xdo $action -n "$id"
	cmd="scratchpad show"
fi

i3-msg "${window_instance} ${cmd}"
