#!/usr/bin/env bash

name="$1"
id=$(xdo id -n $1);

cmd="move scratchpad"

if [ -z "$id" ]; then
	  $TERMINAL --class "$name" -e "tmux new-session -A -s dummy";
	  i3-msg ""
  else
	action='hide';

	if [[ $(xprop -id $id | awk '/window state: / {print $3}') == 'Withdrawn' ]]; then
		action='show';
	fi

	xdo $action -n "$id"
	exec i3-msg [instance="$id"] focus;
fi
