#!/usr/bin/env bash

selection=$(fasd -a -R | awk '{print $2}' | rofi -dmenu -p "Find")

case "$selection" in
	/home/sd/Code/*  | \
	/home/sd/local/scripts/* )
		code "$selection"
		;;
	*)
		xdg-open "$selection"
		;;
esac