#!/usr/bin/env bash

# search root
root_path=$HOME

prompt="-p Folder"

code_folder="Code"

folder_path="$(find ${HOME} -maxdepth 5 -type d \( ! -regex '.*/**/\..*' \) \( ! -regex '.*/node_modules*' \) | \
             sed 's|^'$root_path/'||' | sort | \
             rofi -dmenu -l 40 -i $prompt )"

if [[ ! -z $folder_path ]]; then
    if [[ "$folder_path" == "$root_path" ]]; then
        search_path=$root_path
    else
        search_path="$root_path/$folder_path"
    fi

    if [[ ! -z $search_path ]]; then
        if [[ "$search_path" == *"$code_folder"* ]]; then
            code "$search_path"
        else
            xdg-open "$search_path"
        fi
    fi

fi

exit 0
