#!/usr/bin/env bash

if ! [[ -z "$@" ]]; then
	echo "$@"
	case "$@n" in
	/home/sd/Code/*  | \
	/home/sd/local/scripts/* )
		code "$selection"
		;;
	*)
		xdg-open "$selection"
		;;
	esac

	exit 0;
else
	selection=$(fasd -a -R | awk '{print $2}' | rofi -dmenu -p "Find")

	if ! [[ -z "$selection" ]]; then
		case "$selection" in
			/home/sd/Code/*  | \
			/home/sd/local/scripts/* )
				code "$selection"
				;;
			*)
				xdg-open "$selection"
				;;
		esac
	fi
fi
