#!/usr/bin/env bash
clips_dir=~/local/xclips

primary=$(xclip -selection primary -o)

file_name=$( rofi -e "$primary"; rofi -e "$primary" -dmenu -p "Save As")

if [ -n "$file_name" ]; then
    mkdir -p $clips_dir

    xclip -selection primary -o > "${clips_dir}/${file_name}"
fi