#!/usr/bin/env bash
recent_history=$(fasd -l -t -R)

if [[ -z "$@" ]]; then
    printf "%s\n" "$recent_history"
else

    selected_path="$@"

    if [[ "$selected_path" == *development* || "$selected_path" == *.config* ]]; then
        cmd="code \"$selected_path\"" 
    else
        cmd="xdg-open \"$selected_path\""
    fi

    coproc eval "$cmd" > /dev/null
    fasd -A "$selected_path"
fi