#!/bin/bash
# A fuzzy file-finder and opener based on rofi 
# Requires: rofi, xdg-utils, nerdfonts 
files=/tmp/.file_list

update_list() {
	find $HOME -type d -not -path '*/\.*' 2> /dev/null | sed -e 's/^\./  /g' > /tmp/.file_list
	find $HOME -not -type d 2> /dev/null | sed -E -e '/png$|jpg$|tiff$|gif$|jpeg$|bmp$/ s/^\./  /g' -e '/mp3$|pcm$|wav$|aac$|ogg$|wma$/ s/^\./  /g' -e '/wmv$|webm$|m4v$|mkv$|mov$|flv$|avi$|mp4$/ s/^\./辶  /g' -e 's/^\./  /g' >> /tmp/.file_list
	find .config 2> /dev/null | sed -E -e 's/^\./:~\/./g' >> /tmp/.file_list
}

if [ -e $files ]; then
	# File list exist, use it
	input=$(cat $files | rofi -dmenu -p ' Find')
	# Update the list on the background
	update_list 
else
	# There is no file list, create it and show menu only after that
	update_list
	input=$(cat $files | rofi -dmenu -p '')
fi

	identifier=$(echo $input | cut -d " " -f 1)
	selection=$(echo $input | cut -d " " -f2-)

	echo $identifier
	echo $seledtion
	
	case "$identifier" in
		a)
			selection=https://wiki.archlinux.org/index.php?search="$selection"			#exec $BROWSER https://wiki.archlinux.org/index.php?search="$selection" &> /dev/null &
			;;
		g)
			selection=https://google.com/search?q="$selection"
			;;
		u)
			selection=https://www.ultimate-guitar.com/search.php?search_type=title&value="$selection"
			;;
	esac

	echo
				exec xdg-open "$selection" &> /dev/null
