#!/usr/bin/env bash

selected="$(ps -a -u $USER | \
            rofi -dmenu -i -p "Type to search and select process to kill" \
            awk '{print $1" "$4}')"; 

echo $selected
if [[ ! -z $selected ]]; then
    answer="$(echo -e "Yes\nNo" | \
            rofi -dmenu -i -p "$selected will be killed, are you sure?")"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid 
    fi
fi

exit 0
