#!/bin/bash

declare files
files=$HOME/local/cache/file-list.txt

update_list() {
	whitelist="-not -path '**/\.*' -not -path '*/go/*' -not -path '*/node_modules*' -not -path '*/vendor*' -not -path '*/db_data*' -not -path '*/.*'"

	find "$HOME" -type d "$whitelist" -printf "%T@ %Tc %p\n" 2> /dev/null | sort -u > "$files"
	
	find "$HOME" -not -type d  "$whitelist" -printf "%T@ %Tc %p\n" 2> /dev/null | sed -E -e '/png$|jpg$|tiff$|gif$|jpeg$|bmp$/ s/^\./  /g' -e '/mp3$|pcm$|wav$|aac$|ogg$|wma$/ s/^\./  /g' -e '/wmv$|webm$|m4v$|mkv$|mov$|flv$|avi$|mp4$/ s/^\./辶  /g' -e 's/^\./  /g' >> "$files"
	find .config 2> /dev/null | sed -E -e 's/^\./:~\/./g' >> "$files"
	# find .config 2> /dev/null | sed -E -e 's/^\./:~\/./g' >> $HOME/local/tmp/.file_list
}

if [[ ! -f "$files" ]]; then
	touch "$files"
	eval update_list
elif [[ ! -e "$files" ]]; then
	eval update_list
fi


# if ! [ -e $files ]; then
# 	eval update_list
# fi

declare input
declare input_count

input=$( awk -f "$files" FS=' ' '{print $7}' | rofi -dmenu -p 'Find')

if [[ -z "$@" ]]; then
    printf "%s\n" "$recent_history"
else

	identifier=$(echo "$input" | cut -d " " -f 1)
	search_query=$(echo "$input" | cut -d " " -f2-)

	declare url=''

	case "$identifier" in
		aw)
			url="https://wiki.archlinux.org/index.php?search=${search_query}"
			;;
		ug)
			url="https://www.ultimate-guitar.com/search.php?search_type=title&value=${search_query}"
			;;
		yt)
			url="https://www.youtube.com/results?search_query=${search_query}"
			;;
		*)
			url="https://www.google.com/search?q=${input}"
			;;
	esac

	cmd="xdg-open \"${url}\""
fi

coproc eval "$cmd" > /dev/null

update_list
exit 0