#!/usr/bin/env bash

url=$(rofi -dmenu -p "Video URL")

if [ -n "$url" ]; then
    ytdl_dir=$HOME/Videos/ytdl/
    

    echo $ytdl_dir
      youtube-dl -i -o "{$HOME}/Videos/ytdl/%(title)s.%(ext)s" "{$url}"
fi