#!/usr/bin/env bash

FIREFOX_PROFILE="r0c7v8e7.default-release"

PROFILE_DB="$HOME/.mozilla/firefox/${FIREFOX_PROFILE}/places.sqlite"
TMP_PLACES="/tmp/places"

# Avoid db lock
cp "${PROFILE_DB}" "${TMP_PLACES}"

QUERY="select distinct p.title, p.url from moz_places as p, moz_historyvisits as h, moz_bookmarks as b where substr(h.visit_date, 0, 11) >= strftime('%s', date('now') - 30) and p.id == h.place_id and p.title != '' order by h.visit_date DESC;"

user_input=$(sqlite3 "${TMP_PLACES}" "${QUERY}" | awk -F '|' '{printf "%s [%s]\n", $(NF-1), $NF}' | dmenu -p "Firefox" )


if [[ ! -z "${user_input}" ]]; then
    history_item_url=$( echo $user_input | cut -d "[" -f2 | cut -d "]" -f1 )
            identifier=$(echo "$user_input" | awk '{print $1}' )

            echo $identifier

    if [[ ! -z "${history_item_url}" ]]; then
        URL=$selected_url
    else

        if [[ "$user_input" == http* ]]; then
             URL="$user_input"
        else
            identifier=$(echo "$user_input" | awk '{print $1}' )


        fi
    fi
fi

if [[ ! -z "${ADDR}" ]]; then
    if  [[ "${ADDR[1]}" == "" ]]; then
        IDENTIFIER=$(echo "${ADDR[0]}" | awk '{print $1;}')
        SEARCH_TERMS=$(echo "${ADDR[0]}" |  sed 's/[^ ]* *//')

        case "$IDENTIFIER" in
            "archwiki" | "aw")
                URL="https://wiki.archlinux.org/index.php?search=$SEARCH_TERMS"
                ;;
            "ultimateguitar" | "ug")
                URL="https://www.ultimate-guitar.com/search.php?search_type=title&value=$SEARCH_TERMS"
                ;;
            "youtube" | "yt")
                URL="https://www.youtube.com/results?search_query=$SEARCH_TERMS"
                ;;
            "github" | "gh")
                URL="https://github.com/search?q=$SEARCH_TERMS"
                ;;
            "wordpress" | "wp")
                URL='https://developer.wordpress.org/?s=$SEARCH_TERMS';
                ;;
            *)
            if ! [[ "$IDENTIFIER" == http* ]]; then
                URL="https://www.google.com/search?q=${HISTORY}";
            else
                URL="${ADDR[0]}"
            fi
            ;;
        esac
    else
        URL="${ADDR[1]}"
    fi

    firefox "$URL"
fi

rm "${TMP_PLACES}"