#!/usr/bin/env bash

FIREFOX_PROFILE="r0c7v8e7.default-release"

PROFILE_DB="$HOME/.mozilla/firefox/${FIREFOX_PROFILE}/places.sqlite"
TMP_PLACES="/tmp/places"

# Avoid db lock
cp "${PROFILE_DB}" "${TMP_PLACES}"

query="select distinct p.title, p.url from moz_places as p, moz_historyvisits as h, moz_bookmarks as b where substr(h.visit_date, 0, 11) >= strftime('%s', date('now') - 30) and p.id == h.place_id and p.title != '' order by h.visit_date DESC;"

user_input=$(sqlite3 "${TMP_PLACES}" "${query}" | dmenu -p "Firefox" )

if [[ ! -z "${user_input}" ]]; then
        url=$( echo "$user_input" | awk -F '|' '{print $NF}' )

        if [[ "$url" == *http ]]; then
            URL="$url"
        else
            identifier=$(echo "$user_input" | cut -d ' ' -f1 $1)
            search_query=$(echo "$user_input" | cut -f 2- -d ' ')
            case "$identifier" in
                "archwiki" | "aw")
                    URL="https://wiki.archlinux.org/index.php?search=$search_query"
                    ;;
                "ultimateguitar" | "ug")
                    URL="https://www.ultimate-guitar.com/search.php?search_type=title&value=$SEARCH_TERMS"
                    ;;
                "youtube" | "yt")
                    URL="https://www.youtube.com/results?search_query=$search_query"
                    ;;
                "github" | "gh")
                    URL="https://github.com/search?q=$search_query"
                    ;;
                "wordpress" | "wp")
                    URL="https://developer.wordpress.org/?s=$search_query";
                    ;;
                *)
                    if ! [[ "$identifier" == http* ]]; then
                        URL="https://www.google.com/search?q=$user_input"
                    else
                        URL="$user_input"
                    fi
                ;;
            esac
        fi
    firefox "$URL"
fi

rm "${TMP_PLACES}"