#!/usr/bin/env bash

FIREFOX_PROFILE="r0c7v8e7.default-release"

PROFILE_DB="$HOME/.mozilla/firefox/${FIREFOX_PROFILE}/places.sqlite"
TMP_PLACES="/tmp/places"

# Avoid db lock
cp "${PROFILE_DB}" "${TMP_PLACES}"

query="select distinct p.title, p.url from moz_places as p, moz_historyvisits as h, moz_bookmarks as b where substr(h.visit_date, 0, 11) >= strftime('%s', date('now') - 30) and p.id == h.place_id and p.title != '' order by h.visit_date DESC;"

user_input=$(sqlite3 "${TMP_PLACES}" "${query}" | dmenu -p "Firefox" )

if [[ ! -z "${user_input}" ]]; then

echo $user_input
    identifier=$( echo "$user_input" | awk -F '|' '{print $NF' )

    echo $identifier

    if [[ ! -z "${history_item_url}" ]]; then
        URL=$selected_url
    else
        identifier=$(echo "$user_input" | awk '{print $1}' )
        search_terms=$( echo "$user_input" | cut -d ' ' -f1 $1)

        case "$identifier" in
            "archwiki" | "aw")
                URL="https://wiki.archlinux.org/index.php?search=$SEARCH_TERMS"
                ;;
            "ultimateguitar" | "ug")
                URL="https://www.ultimate-guitar.com/search.php?search_type=title&value=$SEARCH_TERMS"
                ;;
            "youtube" | "yt")
                URL="https://www.youtube.com/results?search_query=$SEARCH_TERMS"
                ;;
            "github" | "gh")
                URL="https://github.com/search?q=$SEARCH_TERMS"
                ;;
            "wordpress" | "wp")
                URL='https://developer.wordpress.org/?s=$SEARCH_TERMS';
                ;;
            *)
            if ! [[ "$identifier" == http* ]]; then
                URL="https://www.google.com/search?q=${HISTORY}";
            else
                URL="${ADDR[0]}"
            fi
            ;;
        esac
    fi


    firefox "$URL"
fi

rm "${TMP_PLACES}"