#!/usr/bin/env bash

firefox_profile="r0c7v8e7.default-release"

profile_db="$HOME/.mozilla/firefox/${firefox_profile}/places.sqlite"
tmp_places="/tmp/places"

echo "${@}"
if [[ -z "$@" ]]; then
    # Avoid db lock
    cp "${profile_db}" "${tmp_places}"

    sql="select distinct p.title, p.url from moz_places as p, moz_historyvisits as h, moz_bookmarks as b where substr(h.visit_date, 0, 11) >= strftime('%s', date('now') - 30) and p.id == h.place_id and p.title != '' order by h.visit_date DESC;"

    query=$(sqlite3 "${tmp_places}" "${sql}")

    echo "$query"
else
    echo "$1"
    rm "${tmp_places}"
fi

# user_input=$(sqlite3 "${tmp_places}" "${query}" | dmenu -p "Firefox" )

# if [[ ! -z "${user_input}" ]]; then
#         history_url=$( echo "$user_input" | awk -F '|' '{print $NF}' )

#         if [[ "$history_url" == http* ]]; then
#             url="$history_url"
#         else
#             identifier=$(echo "$user_input" | cut -d ' ' -f1 $1)
#             search_query=$(echo "$user_input" | cut -f 2- -d ' ')

#             case "$identifier" in
#                 "archwiki" | "aw")
#                     url="https://wiki.archlinux.org/index.php?search=$search_query"
#                     ;;
#                 "ultimateguitar" | "ug")
#                     url="https://www.ultimate-guitar.com/search.php?search_type=title&value=$search_query"
#                     ;;
#                 "youtube" | "yt")
#                     url="https://www.youtube.com/results?search_query=$search_query"
#                     ;;
#                 "github" | "gh")
#                     url="https://github.com/search?q=$search_query"
#                     ;;
#                 "wordpress" | "wp")
#                     url="https://developer.wordpress.org/?s=$search_query";
#                     ;;
#                 *)
#                     if ! [[ "$identifier" == http* ]]; then
#                         url="https://www.google.com/search?q=$user_input"
#                     else
#                         url="$identifier"
#                     fi
#                 ;;
#             esac
#         fi
#     firefox "$url"
# fi