#!/usr/bin/env bash

#lorem_cmd=$(echo '' | dmenu -i -p "Lorem Generator")

user_input=$( $( echo -e "Words\nSentences\nParagraphs" | rofi dmenu -i -p "Lorem Generator") | rofi -dmenu -i -p "Number of Generations" )
echo $user_input
case ${user_input} in
    Words )
        lorem=$(lorem -w "${numberOfGenerations}")
    ;;
    Sentences )
        lorem=$(lorem -s "${numberOfGenerations}")
    ;;
    Paragraphs )
        lorem=$(lorem -p "${numberOfGenerations}")
    ;;
    * )
        lorem=$(lorem -w 25)
    ;;
esac

echo "${lorem}" | xclip -in
