#!/usr/bin/env bash
#lorem_cmd=$(echo '' | dmenu -i -p "Lorem Generator")

input_options=$( rofi -dmenu -p "Generate Lorem Ipsum" )

if [[ ! -z == "$input_options" ]]; then
    echo ${input_options[0]}
    case ${[cmd_options]} in
        Words )
            options=$(lorem -w "${numberOfGenerations}")
        ;;
        Sentences )
            options=$(lorem -s "${numberOfGenerations}")
        ;;
        Paragraphs )
            options=$(-p "${numberOfGenerations}")
        ;;
        * )
            lorem=$(lorem -w 25)
        ;;
    esac

    lorem  | xclip -in

fi


