#!/usr/bin/env bash

#lorem_cmd=$(echo '' | dmenu -i -p "Lorem Generator")

user_input=$( $( echo -e "Words\nSentences\nParagraphs" | rofi dmenu -i -p "Lorem Generator") | rofi -dmenu -i -p "Number of Generations" )
echo $user_input
case ${user_input} in
    Words )
        lorem_cmd=$(lorem -w "${numberOfGenerations}")
    ;;
    Sentences )
        lorem_cmd=$(lorem -s "${numberOfGenerations}")
    ;;
    Paragraphs )
        lorem_cmd=$(lorem -p "${numberOfGenerations}")
    ;;
    * )
        lorem_cmd=$(lorem -w 25)
    ;;
esac

$lorem_cmd | xclip -in
