#!/usr/bin/env bash
#lorem_cmd=$(echo '' | dmenu -i -p "Lorem Generator")

read -ra user_input <<< $( rofi -dmenu -p "Generate Lorem Ipsum" )


if [[ ! -z "$input_options" ]]; then
    case ${[cmd_options]} in
        Words )
            options=$(lorem -w "${numberOfGenerations}")
        ;;
        Sentences )
            options=$(lorem -s "${numberOfGenerations}")
        ;;
        Paragraphs )
            options=$(-p "${numberOfGenerations}")
        ;;
        * )
            lorem=$(lorem -w 25)
        ;;
    esac

    lorem  | xclip -in

fi


