#!/usr/bin/env bash

#lorem_cmd=$(echo '' | dmenu -i -p "Lorem Generator")

user_input=$( dmenu -i -p  "Generation Count" | $( echo -e "Words\nSentences\nParagraphs" | dmenu -i -p "Lorem Generator"))
echo $user_input
case ${user_input} in
    Words )
        lorem_cmd=$(lorem -w "${numberOfGenerations}")
    ;;
    Sentences )
        lorem_cmd=$(lorem -s "${numberOfGenerations}")
    ;;
    Paragraphs )
        lorem_cmd=$(lorem -p "${numberOfGenerations}")
    ;;
    * )
        lorem_cmd=$(lorem -w 25)
    ;;
esac

lorem_cmd | xclip -in
