#!/usr/bin/env bash

# terminal to open manual
terminal="urxvt"

scripts_dir=${SCRIPTS_DIR:-$HOME/.local/scripts}

input=$(find "$scripts_dir" -type f -not -path '*/\.git/*' | sort | dmenu -l 100 -i -p "Run Script")
read -ra input_cmd <<< "${input}"

if [ ! -z "${input_cmd}" ];  then
    if [ ! -z "${input_cmd[1]}" ]; then
        cmd="${input_cmd[@]}"
    else
        cmd="${input_cmd}"
    fi

    $terminal --hold -e zsh -c "${cmd}"
fi
