#!/usr/bin/env bash

prompt="-p Path:"
root_path="$HOME"

find_path="$(find $root_path -maxdepth 3 -type d | \
             sed 's|^'$root_path/'||' | \
             dmenu -i -l 30 $prompt)"

             echo "{$root_path}{$find_path}"

if [[ ! -z "$find_path" ]]; then
    xdg-open "$find_path"
fi

exit 0
