#!/usr/bin/env bash

firefox_profile="r0c7v8e7.default-release"

profile_db="$HOME/.mozilla/firefox/${firefox_profile}/places.sqlite"
tmp_places="/tmp/places"

# Avoid db lock
cp "${profile_db}" "${tmp_places}"

if [[ -z "$1" ]]; then
    sql="select distinct p.title, p.url \
        from moz_places as p, moz_historyvisits as h, moz_bookmarks as b \
        where substr(h.visit_date, 0, 11) >= strftime('%s', date('now') - 30) \
        and p.id == h.place_id and p.title != '' order by h.visit_date DESC;"

    query=$(sqlite3 "${tmp_places}" "${sql}")

    echo "$query";
else
    url=$(echo "$@" | egrep -o 'https?://[^ ]+')
    firefox "$url"
    exec i3-msg [class="firefox" instance="Navigator"] focus > /dev/null 2>&1
    exit 0;
fi




# user_input=$(sqlite3 "${tmp_places}" "${query}" | dmenu -p "Firefox" )
